name: Check & fix styling

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs.dist.php --allow-risky=yes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: php-cs-fixer/patch
          delete-branch: true
          commit-message: Linted php files with PHP-CS-Fixer
          title: Fix styling
          body: Fix coding style accordign to the rules set in the project.

